kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: cert-manager
  namespace: fleet-default
spec:
  repo: https://github.com/atoy3731/kubewarden-fleet.git
  targets:
  - name: protected
    clusterSelector:
      matchLabels:
        protected: enabled
  paths:
  - "./kubewarden/crds"
